In [68]:
import numpy as np

In [69]:
l = [1,2,3,4]

In [70]:
np.array(l)

array([1, 2, 3, 4])

In [71]:
ar = np.sum(l)

In [72]:
type(ar)

numpy.int32

In [73]:
np.array([[1,2],[3,4]])
#2 dimesional array

array([[1, 2],
       [3, 4]])

In [74]:
np.asarray(l)

array([1, 2, 3, 4])

In [75]:
a = [1,2,3]

In [76]:
type(a)

list

In [77]:
b = np.asarray(a)

In [78]:
type(b)

numpy.ndarray

In [79]:
b

array([1, 2, 3])

In [80]:
c = np.matrix(a)

In [81]:
np.asanyarray(b)

array([1, 2, 3])

In [82]:
np.asanyarray(c)
#still matrix

matrix([[1, 2, 3]])

In [83]:
a = np.array(l)

In [84]:
a

array([1, 2, 3, 4])

In [85]:
d = a

In [86]:
a = [1,2,34]

In [87]:
a =np.array(a)

In [88]:
d = a

In [89]:
d[0]

1

In [90]:
d = np.copy(a)

In [91]:
d

array([ 1,  2, 34])

In [92]:
a

array([ 1,  2, 34])

In [93]:
a[1] = 400

In [94]:
a

array([  1, 400,  34])

In [95]:
d

array([ 1,  2, 34])

In [96]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [97]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [98]:
itr = [i*i for i in range(5)]

In [99]:
itr

[0, 1, 4, 9, 16]

In [100]:
np.fromiter(itr,float)

array([ 0.,  1.,  4.,  9., 16.])

In [101]:
np.fromstring("234 234",sep = ' ')

array([234., 234.])

In [102]:
#Numpy datatypes

In [103]:
l = [1,2,3,4,4]

In [104]:
ar = np.array(l)

In [105]:
ar

array([1, 2, 3, 4, 4])

In [106]:
ar.ndim

1

In [107]:
ar1 = np.array([[1,2],[3,4],[5,6]]) 

In [108]:
ar1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
ar1.ndim

2

In [110]:
ar.shape

(5,)

In [111]:
ar1.shape

(3, 2)

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'

In [ ]:
list(range(0,5))

In [115]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [116]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [118]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [120]:
on = np.ones((2,3,3))

In [121]:
on+5

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [122]:
on*6

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [124]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [126]:
np.eye(4)
#idenetity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [127]:
np.linspace(2,3,20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [129]:
np.logspace(2,4,10 ,base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [131]:
arr = np.random.randn(3,4)

In [132]:
import pandas as pd

In [133]:
pd.DataFrame(arr)

0         1         2         3
0  0.647309 -0.330108 -0.376672  0.821390
1 -0.047664  0.126711 -0.045650 -0.395573
2 -2.349521 -0.173261 -2.034783  0.490019

In [134]:
np.random.rand(3,4)

array([[0.24433562, 0.30424678, 0.78983875, 0.95621586],
       [0.54372122, 0.48021995, 0.74783526, 0.88098904],
       [0.26739515, 0.53280253, 0.25892822, 0.9517806 ]])

In [138]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv("test.csv")


In [140]:
arr.reshape(6,-1)

array([[ 0.64730912, -0.33010812],
       [-0.37667238,  0.8213904 ],
       [-0.04766383,  0.1267111 ],
       [-0.04564966, -0.39557261],
       [-2.34952121, -0.17326135],
       [-2.0347826 ,  0.49001868]])

In [142]:
arr.reshape(6,-1889788989)

array([[ 0.64730912, -0.33010812],
       [-0.37667238,  0.8213904 ],
       [-0.04766383,  0.1267111 ],
       [-0.04564966, -0.39557261],
       [-2.34952121, -0.17326135],
       [-2.0347826 ,  0.49001868]])

In [144]:
arr = np.random.randint(1,100,(5,5))

In [145]:
arr

array([[95, 46, 22, 98, 75],
       [38, 58, 42, 11, 39],
       [13, 50, 31, 40,  7],
       [59, 50, 62, 13, 47],
       [47,  2,  7, 75, 18]])

In [146]:
arr>50

array([[ True, False, False,  True,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [ True, False,  True, False, False],
       [False, False, False,  True, False]])

In [148]:
arr[arr>50]
#extract data

array([95, 98, 75, 58, 59, 62, 75])

In [151]:
arr[0][0] = 50000

In [152]:
arr

array([[50000,    46,    22,    98,    75],
       [   38,    58,    42,    11,    39],
       [   13,    50,    31,    40,     7],
       [   59,    50,    62,    13,    47],
       [   47,     2,     7,    75,    18]])

In [153]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [155]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [1, 1, 2]])

In [156]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [154]:
arr1*arr2

array([[1, 2, 1],
       [2, 4, 1],
       [1, 2, 2]])

In [158]:
arr1@arr2
#array multiplication can done by "@"

array([[4, 7, 4],
       [5, 8, 5],
       [4, 7, 4]])

In [159]:
arr1/0

C:\Users\admin\AppData\Local\Temp\ipykernel_3312\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [160]:
#numpy Broadcasting

In [162]:
arr = np.zeros((4,4))

In [163]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [169]:
row = np.array([[1,2,3,4]])

In [165]:
row

array([1, 2, 3, 4])

In [166]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [168]:
arr.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [170]:
row.T

array([[1],
       [2],
       [3],
       [4]])

In [171]:
row.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [173]:
np.random.randint(1,4,(3,4))

array([[1, 1, 1, 2],
       [3, 2, 3, 3],
       [3, 2, 2, 3]])

# NUmpy part 2

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[5, 3, 2, 6],
       [3, 5, 3, 6],
       [9, 6, 9, 3]])

In [5]:
arr.reshape(2,6)

array([[5, 3, 2, 6, 3, 5],
       [3, 6, 9, 6, 9, 3]])

In [6]:
arr.reshape(2,7)
#

ValueError: cannot reshape array of size 12 into shape (2,7)

In [7]:
arr.reshape(2,6)

array([[5, 3, 2, 6, 3, 5],
       [3, 6, 9, 6, 9, 3]])

In [8]:
arr.T

array([[5, 3, 9],
       [3, 5, 6],
       [2, 3, 9],
       [6, 6, 3]])

In [9]:
arr.flatten()

array([5, 3, 2, 6, 3, 5, 3, 6, 9, 6, 9, 3])

In [10]:
arr1 = np.array([1,2,3,4,5,6])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis = 0)

array([[1, 2, 3, 4, 5, 6]])

In [14]:
data = np.array([[1],[2],[3]])

In [15]:
data

array([[1],
       [2],
       [3]])

In [16]:
np.squeeze(data)

array([1, 2, 3])

In [17]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
np.roll(arr1,2)

array([5, 6, 1, 2, 3, 4])

In [19]:
arr1

array([1, 2, 3, 4, 5, 6])

In [20]:
np.diag(arr1)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [21]:
#numpy binary operations

In [25]:
arr2 = np.random.randint(1,10,(3,4))

In [26]:
arr1

array([[7, 6, 4, 4],
       [7, 7, 8, 3],
       [4, 7, 2, 3]])

In [27]:
arr2

array([[1, 8, 8, 2],
       [9, 9, 3, 4],
       [3, 4, 2, 6]])

In [28]:
arr1*arr2

array([[ 7, 48, 32,  8],
       [63, 63, 24, 12],
       [12, 28,  4, 18]])

In [29]:
arr1+arr2

array([[ 8, 14, 12,  6],
       [16, 16, 11,  7],
       [ 7, 11,  4,  9]])

In [30]:
arr1 - arr2

array([[ 6, -2, -4,  2],
       [-2, -2,  5, -1],
       [ 1,  3,  0, -3]])

In [31]:
arr1 %arr2

array([[0, 6, 4, 0],
       [7, 7, 2, 3],
       [1, 3, 0, 3]])

In [32]:
arr1**arr2

array([[       7,  1679616,    65536,       16],
       [40353607, 40353607,      512,       81],
       [      64,     2401,        4,      729]])

In [33]:
arr1&arr2

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 4, 2, 2]])

In [34]:
-arr1

array([[-7, -6, -4, -4],
       [-7, -7, -8, -3],
       [-4, -7, -2, -3]])

In [35]:
-arr2

array([[-1, -8, -8, -2],
       [-9, -9, -3, -4],
       [-3, -4, -2, -6]])

In [36]:
arr1|arr2

array([[ 7, 14, 12,  6],
       [15, 15, 11,  7],
       [ 7,  7,  2,  7]])

In [37]:
arr1>arr2

array([[ True, False, False,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

#numpy string

In [39]:
arr = np.array(["Pratyush","Kumar"])

In [40]:
arr

array(['Pratyush', 'Kumar'], dtype='<U8')

In [41]:
np.char.upper(arr)

array(['PRATYUSH', 'KUMAR'], dtype='<U8')

In [42]:
np.char.title(arr)

array(['Pratyush', 'Kumar'], dtype='<U8')

In [43]:
#mathmatical fun

In [44]:
arr1

array([[7, 6, 4, 4],
       [7, 7, 8, 3],
       [4, 7, 2, 3]])

In [45]:
np.sin(arr1)

array([[ 0.6569866 , -0.2794155 , -0.7568025 , -0.7568025 ],
       [ 0.6569866 ,  0.6569866 ,  0.98935825,  0.14112001],
       [-0.7568025 ,  0.6569866 ,  0.90929743,  0.14112001]])

In [46]:
np.cos(arr1)

array([[ 0.75390225,  0.96017029, -0.65364362, -0.65364362],
       [ 0.75390225,  0.75390225, -0.14550003, -0.9899925 ],
       [-0.65364362,  0.75390225, -0.41614684, -0.9899925 ]])

In [47]:
np.tan(arr1)

array([[ 0.87144798, -0.29100619,  1.15782128,  1.15782128],
       [ 0.87144798,  0.87144798, -6.79971146, -0.14254654],
       [ 1.15782128,  0.87144798, -2.18503986, -0.14254654]])

In [48]:
np.tanh(arr1)

array([[0.99999834, 0.99998771, 0.9993293 , 0.9993293 ],
       [0.99999834, 0.99999834, 0.99999977, 0.99505475],
       [0.9993293 , 0.99999834, 0.96402758, 0.99505475]])

In [49]:
np.log10(arr1)

array([[0.84509804, 0.77815125, 0.60205999, 0.60205999],
       [0.84509804, 0.84509804, 0.90308999, 0.47712125],
       [0.60205999, 0.84509804, 0.30103   , 0.47712125]])

In [50]:
np.exp(arr1)

array([[1096.63315843,  403.42879349,   54.59815003,   54.59815003],
       [1096.63315843, 1096.63315843, 2980.95798704,   20.08553692],
       [  54.59815003, 1096.63315843,    7.3890561 ,   20.08553692]])

In [51]:
np.sqrt(arr1)

array([[2.64575131, 2.44948974, 2.        , 2.        ],
       [2.64575131, 2.64575131, 2.82842712, 1.73205081],
       [2.        , 2.64575131, 1.41421356, 1.73205081]])

In [53]:
np.power(arr1,2)

array([[49, 36, 16, 16],
       [49, 49, 64,  9],
       [16, 49,  4,  9]], dtype=int32)

In [54]:
np.mean(arr1)

5.166666666666667

In [56]:
np.median(arr1)

5.0

In [57]:
np.var(arr1)

3.8055555555555554

In [58]:
np.min(arr1)

2

In [59]:
np.max(arr1)

8

In [60]:
#sorting searching an counting 

In [61]:
arr1

array([[7, 6, 4, 4],
       [7, 7, 8, 3],
       [4, 7, 2, 3]])

In [65]:
arr = np.array([1,2,3,8,9,5,0,3,6,4])

In [66]:
arr

array([1, 2, 3, 8, 9, 5, 0, 3, 6, 4])

In [67]:
np.sort(arr)

array([0, 1, 2, 3, 3, 4, 5, 6, 8, 9])

In [68]:
np.searchsorted(arr,34)

10

In [69]:
arr1 = np.array([1,345,454,0,0,0,0,0,0,0])

In [70]:
np.count_nonzero(arr1)

3

In [71]:
np.where(arr>6)

(array([3, 4], dtype=int64),)

In [72]:
np.extract(arr>3,arr)

array([8, 9, 5, 6, 4])

In [73]:
#numpy - byte swapping

In [74]:
arr.byteswap()

array([ 16777216,  33554432,  50331648, 134217728, 150994944,  83886080,
               0,  50331648, 100663296,  67108864])

In [75]:
a = np.copy(arr)

In [76]:
a 

array([1, 2, 3, 8, 9, 5, 0, 3, 6, 4])

In [78]:
b = arr.view()

In [79]:
b[0]

1

In [80]:
#numpy -Matrix Library

In [81]:
import numpy.matlib as nm

In [82]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [83]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [84]:
#numpy _linear Algebra

In [85]:
arr1

array([  1, 345, 454,   0,   0,   0,   0,   0,   0,   0])

In [86]:
arr

array([1, 2, 3, 8, 9, 5, 0, 3, 6, 4])

In [88]:
np.dot(arr1,arr)

2053